[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "check-added-large-files" },
  { id = "check-merge-conflict" },
  { id = "check-case-conflict" },
  { id = "check-symlinks" },
  { id = "destroyed-symlinks" },
  { id = "detect-private-key" },
  { id = "mixed-line-ending" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "nixfmt"
name = "nixfmt"
language = "system"
entry = "nixfmt --check"
files = '\.nix$'

[[repos.hooks]]
id = "statix"
name = "statix"
language = "system"
entry = "statix check ."
pass_filenames = false
files = '\.nix$'
