{ lib, pkgs, ... }:
let
  pywalfoxHost = pkgs.writeShellApplication {
    name = "pywalfox-host";
    runtimeInputs = [ pkgs.pywalfox-native ];
    text = "pywalfox start";
  };
in
{
  programs.librewolf = {
    enable = true;
    policies.ExtensionSettings."pywalfox@frewacom.org" = {
      installation_mode = "force_installed";
      install_url = "https://addons.mozilla.org/firefox/downloads/latest/pywalfox/latest.xpi";
    };
  };

  home.file.".librewolf/native-messaging-hosts/pywalfox.json".text = builtins.toJSON {
    name = "pywalfox";
    description = "Automatically theme your browser using the colors generated by Pywal";
    path = lib.getExe pywalfoxHost;
    type = "stdio";
    allowed_extensions = [ "pywalfox@frewacom.org" ];
  };

  home.packages = with pkgs; [
    brave
    pywalfox-native
    tor-browser
    ungoogled-chromium
  ];

  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "text/html" = "librewolf.desktop";
      "x-scheme-handler/http" = "librewolf.desktop";
      "x-scheme-handler/https" = "librewolf.desktop";
    };
  };
}
