[UPower]
AllowRiskyCriticalPowerAction=false
CriticalPowerAction=PowerOff
EnableWattsUpPro=false
IgnoreLid=false
NoPollBatteries=false
PercentageAction=2
PercentageCritical=5
PercentageLow=20
TimeAction=120
TimeCritical=300
TimeLow=1200
UsePercentageForPolicy=true
