[keybinds]
"Mod+Escape" = "session-quit"
"Mod+F1" = "window-focus-next"

"Mod+Left" = "window-focus-left"
"Mod+H" = "window-focus-left"
"Mod+Right" = "window-focus-right"
"Mod+L" = "window-focus-right"
"Mod+Up" = "window-focus-up"
"Mod+K" = "window-focus-up"
"Mod+Down" = "window-focus-down"
"Mod+J" = "window-focus-down"

"Mod+Shift+Left" = "column-move-left"
"Mod+Shift+H" = "column-move-left"
"Mod+Shift+Right" = "column-move-right"
"Mod+Shift+L" = "column-move-right"
"Mod+Shift+Up" = "window-move-up"
"Mod+Shift+K" = "window-move-up"
"Mod+Shift+Down" = "window-move-down"
"Mod+Shift+J" = "window-move-down"

"Mod+Comma" = "window-consume-left"
"Mod+Period" = "window-expel-right"
"Mod+R" = "window-cycle-width"
"Mod+Shift+R" = "window-cycle-width-back"
"Mod+F" = "window-toggle-fullscreen"
"Mod+Ctrl+F" = "window-toggle-maximize"
"Mod+M" = "window-toggle-maximize-to-edges"
"Mod+T" = "window-toggle-floating"
"Mod+P" = "window-toggle-pinned"
"Mod+O" = { action = "overview-toggle", repeat = false }

"Mod+1" = "workspace-switch:1"
"Mod+2" = "workspace-switch:2"
"Mod+3" = "workspace-switch:3"
"Mod+4" = "workspace-switch:4"
"Mod+5" = "workspace-switch:5"
"Mod+6" = "workspace-switch:6"
"Mod+7" = "workspace-switch:7"
"Mod+8" = "workspace-switch:8"
"Mod+9" = "workspace-switch:9"
"Mod+KP_1" = "workspace-switch:1"
"Mod+KP_2" = "workspace-switch:2"
"Mod+KP_3" = "workspace-switch:3"
"Mod+KP_4" = "workspace-switch:4"
"Mod+KP_5" = "workspace-switch:5"
"Mod+KP_6" = "workspace-switch:6"
"Mod+KP_7" = "workspace-switch:7"
"Mod+KP_8" = "workspace-switch:8"
"Mod+KP_9" = "workspace-switch:9"
"Mod+Shift+1" = "window-move-to-workspace:1"
"Mod+Shift+2" = "window-move-to-workspace:2"
"Mod+Shift+3" = "window-move-to-workspace:3"
"Mod+Shift+4" = "window-move-to-workspace:4"
"Mod+Shift+5" = "window-move-to-workspace:5"
"Mod+Shift+6" = "window-move-to-workspace:6"
"Mod+Shift+7" = "window-move-to-workspace:7"
"Mod+Shift+8" = "window-move-to-workspace:8"
"Mod+Shift+9" = "window-move-to-workspace:9"
"Mod+Shift+KP_1" = "window-move-to-workspace:1"
"Mod+Shift+KP_2" = "window-move-to-workspace:2"
"Mod+Shift+KP_3" = "window-move-to-workspace:3"
"Mod+Shift+KP_4" = "window-move-to-workspace:4"
"Mod+Shift+KP_5" = "window-move-to-workspace:5"
"Mod+Shift+KP_6" = "window-move-to-workspace:6"
"Mod+Shift+KP_7" = "window-move-to-workspace:7"
"Mod+Shift+KP_8" = "window-move-to-workspace:8"
"Mod+Shift+KP_9" = "window-move-to-workspace:9"

"Mod+WheelUp" = "window-focus-left"
"Mod+WheelDown" = "window-focus-right"
