## name: Orikalk Lapis Dark
## author: Orikalk
## license: MIT
## upstream: https://raw.githubusercontent.com/orikalk/kitty/master/themes/Orikalk%20Lapis%20Dark.conf
## blurb: Gold-accented dark theme on lapis surfaces.

foreground #c9e9fd
background #1d2b38
selection_foreground #1d2b38
selection_background #e6be8a

cursor #e6be8a
cursor_text_color #1d2b38

scrollbar_handle_color #91aabc
scrollbar_track_color #445564

url_color #e6be8a

active_border_color #e6be8a
inactive_border_color #6a8090
bell_border_color #e6be8a

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground #0c1721
active_tab_background #e6be8a
inactive_tab_foreground #c9e9fd
inactive_tab_background #18242f
tab_bar_background #0c1721

mark1_foreground #1d2b38
mark1_background #c19edb
mark2_foreground #1d2b38
mark2_background #e6be8a
mark3_foreground #1d2b38
mark3_background #7eb976

color0 #445564
color8 #566a7a
color1 #f18e86
color9 #ff9b92
color2 #7eb976
color10 #8ac682
color3 #e6be8a
color11 #f3cb96
color4 #6db3e4
color12 #7ac0f1
color5 #c19edb
color13 #ceabe8
color6 #60bab7
color14 #6dc7c4
color7 #a3bfd1
color15 #c9e9fd
