## name: Orikalk Lapis Light
## author: Orikalk
## license: MIT
## upstream: https://raw.githubusercontent.com/orikalk/kitty/master/themes/Orikalk%20Lapis%20Light.conf
## blurb: Gold-accented light theme on lapis surfaces.

foreground #584b3c
background #f1e9d2
selection_foreground #f1e9d2
selection_background #4275a6

cursor #4275a6
cursor_text_color #f1e9d2

scrollbar_handle_color #867a68
scrollbar_track_color #c3b9a4

url_color #4275a6

active_border_color #4275a6
inactive_border_color #a59a86
bell_border_color #926f34

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground #e1d8c2
active_tab_background #4275a6
inactive_tab_foreground #584b3c
inactive_tab_background #e9e1ca
tab_bar_background #e1d8c2

mark1_foreground #f1e9d2
mark1_background #81619b
mark2_foreground #f1e9d2
mark2_background #4275a6
mark3_foreground #f1e9d2
mark3_background #538032

color0 #675b4a
color8 #766a59
color1 #b3544f
color9 #c0605a
color2 #538032
color10 #5e8c3e
color3 #926f34
color11 #9e7b40
color4 #4275a6
color12 #4e81b3
color5 #81619b
color13 #8d6da8
color6 #008282
color14 #1e8e8e
color7 #b4a995
color15 #c3b9a4
